#!/bin/sh
#
# prowler: delete unwanted files that otherwise pollute $HOME
#
# Copyright 2010 Tom Vincent <http://www.tlvince.com/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

CONF_DIR="${XDG_CONFIG_HOME:-"$HOME/.config"}/prowler"
DATA_DIR="${XDG_DATA_HOME:-"$HOME/.local/share"}/prowler"
WATCH_FILES="$CONF_DIR/watchfiles"
CONFIG="$CONF_DIR/config"

##
# User definable action when inotify event occurs.
# Override in $CONFIG
#
before_rm ()
{
    return
}

LOG=0
[ -f "$CONFIG" ] && . "$CONFIG"

LOG_FILE="${LOG_FILE:-"$DATA_DIR/prowler.log"}"

[ "$LOG" != '0' ] && mkdir -p "$(dirname "$LOG_FILE")" 2>/dev/null

inotifywait -qm --format '%f' -e create "$HOME" | grep --line-buffered -x -f "$WATCH_FILES" | while read file; do
        prefix="$(date +'%F %R') :: $HOME/$file "
	if before_rm "$file"
	then
		if rm -rf "$HOME/$file"
		then
			[ "$LOG" != '0' ] && echo "$prefix deleted" >> $LOG_FILE
		else
			[ "$LOG" != '0' ] && echo "$prefix delete ERROR, rm returned $?" >> $LOG_FILE
		fi
	else
		[ "$LOG" != '0' ] && echo "$prefix delete skipped, before_rm returned $?" >> $LOG_FILE
	fi

done
