#!/bin/sh
#
# prowler: delete unwanted files that otherwise pollute $HOME
#
# Copyright 2010 Tom Vincent <http://www.tlvince.com/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

CONF_DIR="${XDG_CONFIG_HOME:-"$HOME/.config"}/prowler"
WATCH_FILES="$CONF_DIR/watchfiles"
CONFIG="$CONF_DIR/config"
#LOG="${XDG_CACHE_HOME:-"$HOME/.cache"}/prowler.log"

##
# User definable action when inotify event occurs.
# Override in $CONFIG
#
action()
{
    return
}

[ -f "$CONFIG" ] && . "$CONFIG"

inotifywait -qm --format '%f' -e create "$HOME" | grep --line-buffered -x -f "$WATCH_FILES" | while read file; do
        rm -rf "$HOME/$file"
        #echo "$(date +"%F %R") :: Deleted $HOME/$file" >> $LOG
        action "$HOME/$file" &
done
