#!/bin/bash
#
# prowler: delete unwanted files that otherwise pollute $HOME
#
# Copyright 2010 Tom Vincent <http://www.tlvince.com/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

WATCH_FILES="${XDG_CONFIG_HOME:-"$HOME/.config"}/${0##*/}/badfiles" # Bash-ism
#LOG="${XDG_CACHE_HOME:-"$HOME/.cache"}/${0##*/}.log"

inotifywait -qm --format '%f' -e create "$HOME" | while read file; do
    if $(grep -Fq "$file" "$WATCH_FILES"); then
        rm -rf "$HOME/$file"
        #echo "$(date +"%F %R") :: Deleted $HOME/$file" >> $LOG
    fi
done
